### ISSUE TITLE
DIRT Rally 2 Log (690790) 

### ISSUE THREAD

**Issue by leillo1975** [berarma/ffbtools#1]
**Name of the game:** DIRT Rally 2
**Steam ID:** 690790
**Game version:** 1.9.0
**Game Type (native/proton/wine):** Proton
**Proton/Wine version:** 4.11-7
**Wheel Model:** Logitech G29
**Compatibility Mode:** None
**Distribution:** Ubuntu 18.04.3
**Kernel version:** 5.0

**Force Feedback present:** No
**Symptoms or Special Notes:** The game is executed without FFB fixes 

[DirtRally2-20191019124906.log](https://github.com/berarma/ffbtools/files/3746577/DirtRally2-20191019124906.log)

**Comment by berarma** [comment]
The same problem has been reported for a G920 wheel: https://github.com/ValveSoftware/Proton/issues/2366#issuecomment-544434688

FFB works for both wheels when the `--update-fix` is applied.

**Comment by berarma** [comment]
The latest version of ffbtools might help us know why the effects are lost. Please, can someone update ffbtools and create a new log file?

**Comment by leillo1975** [comment]
Here is the log with the updated version of FFBTools:
[DirtRally2-20191028190619.log](https://github.com/berarma/ffbtools/files/3780036/DirtRally2-20191028190619.log)

**Comment by leillo1975** [comment]
And this is the log with --features-hack enabled:
[DirtRally2-20191029235035.log](https://github.com/berarma/ffbtools/files/3786125/DirtRally2-20191029235035.log)

**Comment by berarma** [comment]
This game is already fixed by torvalds/linux@09264098ff153f60866039d60b31d39b66f55a31 in Linux 5.7.
