### ISSUE TITLE
[installation] makefile error

### ISSUE THREAD

**Issue by showeye** [berarma/ffbtools#10]
Hello, runnig `make` gives me the following output:

`cc -I./src -MMD -MP  -m32 -fPIC -shared src/ffbwrapper.c -o build/libffbwrapper-i386.so -ldl
src/ffbwrapper.c: In function ‘ioctl’:
src/ffbwrapper.c:164:20: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int’ [-Wformat=]
             report("> IOCTL: Remove effect from memory: %ld.", (intptr_t)argp);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~
src/ffbwrapper.c:46:50: note: in definition of macro ‘report’
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                                                  ^~~~~~~~~~~
src/ffbwrapper.c:271:20: warning: ‘%s’ directive output may be truncated writing up to 511 bytes into a region of size 457 [-Wformat-truncation=]
             report("> IOCTL: Upload effect to device. id: %d dir: %d type: %s, %s, params: { %s }", effect->id, direction, type, string, effect_params);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                               ~~~~~~
src/ffbwrapper.c:46:50: note: in definition of macro ‘report’
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                                                  ^~~~~~~~~~~
src/ffbwrapper.c:46:21: note: ‘snprintf’ output 70 or more bytes (assuming 1092) into a destination of size 512
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ffbwrapper.c:271:13: note: in expansion of macro ‘report’
             report("> IOCTL: Upload effect to device. id: %d dir: %d type: %s, %s, params: { %s }", effect->id, direction, type, string, effect_params);
             ^~~~~~
src/ffbwrapper.c:276:24: warning: ‘%s’ directive output may be truncated writing up to 511 bytes into a region of size 458 [-Wformat-truncation=]
                 report("> IOCTL: Upload effect to device id: %d dir: %d type: %s, %s, params: { %s } (direction_fix)", effect->id, direction, type, string, effect_params);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                               ~~~~~~
src/ffbwrapper.c:46:50: note: in definition of macro ‘report’
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                                                  ^~~~~~~~~~~
src/ffbwrapper.c:46:21: note: ‘snprintf’ output 85 or more bytes (assuming 1107) into a destination of size 512
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ffbwrapper.c:276:17: note: in expansion of macro ‘report’
                 report("> IOCTL: Upload effect to device id: %d dir: %d type: %s, %s, params: { %s } (direction_fix)", effect->id, direction, type, string, effect_params);
                 ^~~~~~
src/ffbwrapper.c:309:28: warning: ‘%s’ directive output may be truncated writing up to 511 bytes into a region of size between 497 and 507 [-Wformat-truncation=]
                     report("< %d, %s", result, string);
                            ^~~~~~~~~~          ~~~~~~
src/ffbwrapper.c:46:50: note: in definition of macro ‘report’
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                                                  ^~~~~~~~~~~
src/ffbwrapper.c:46:21: note: ‘snprintf’ output between 6 and 527 bytes into a destination of size 512
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ffbwrapper.c:309:21: note: in expansion of macro ‘report’
                     report("< %d, %s", result, string);
                     ^~~~~~
cc -I./src -MMD -MP  -fPIC -shared src/ffbwrapper.c -o build/libffbwrapper-x86_64.so -ldl
src/ffbwrapper.c: In function ‘ioctl’:
src/ffbwrapper.c:271:20: warning: ‘%s’ directive output may be truncated writing up to 511 bytes into a region of size 457 [-Wformat-truncation=]
             report("> IOCTL: Upload effect to device. id: %d dir: %d type: %s, %s, params: { %s }", effect->id, direction, type, string, effect_params);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                               ~~~~~~
src/ffbwrapper.c:46:50: note: in definition of macro ‘report’
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                                                  ^~~~~~~~~~~
src/ffbwrapper.c:46:21: note: ‘snprintf’ output 70 or more bytes (assuming 1092) into a destination of size 512
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ffbwrapper.c:271:13: note: in expansion of macro ‘report’
             report("> IOCTL: Upload effect to device. id: %d dir: %d type: %s, %s, params: { %s }", effect->id, direction, type, string, effect_params);
             ^~~~~~
src/ffbwrapper.c:276:24: warning: ‘%s’ directive output may be truncated writing up to 511 bytes into a region of size 458 [-Wformat-truncation=]
                 report("> IOCTL: Upload effect to device id: %d dir: %d type: %s, %s, params: { %s } (direction_fix)", effect->id, direction, type, string, effect_params);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                               ~~~~~~
src/ffbwrapper.c:46:50: note: in definition of macro ‘report’
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                                                  ^~~~~~~~~~~
src/ffbwrapper.c:46:21: note: ‘snprintf’ output 85 or more bytes (assuming 1107) into a destination of size 512
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ffbwrapper.c:276:17: note: in expansion of macro ‘report’
                 report("> IOCTL: Upload effect to device id: %d dir: %d type: %s, %s, params: { %s } (direction_fix)", effect->id, direction, type, string, effect_params);
                 ^~~~~~
src/ffbwrapper.c:309:28: warning: ‘%s’ directive output may be truncated writing up to 511 bytes into a region of size between 497 and 507 [-Wformat-truncation=]
                     report("< %d, %s", result, string);
                            ^~~~~~~~~~          ~~~~~~
src/ffbwrapper.c:46:50: note: in definition of macro ‘report’
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                                                  ^~~~~~~~~~~
src/ffbwrapper.c:46:21: note: ‘snprintf’ output between 6 and 527 bytes into a destination of size 512
 #define report(...) snprintf(report_string, 512, __VA_ARGS__); output(report_string);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ffbwrapper.c:309:21: note: in expansion of macro ‘report’
                     report("< %d, %s", result, string);
`

OS: Ubuntu 19.04 64bit
Kernel: 5.0.0-32-generic

Any ideas?

**Comment by berarma** [comment]
They are only warnings, everything should have been correctly built. I'll try to fix the warnings, they warn about some possible crash bugs (only the tool would crash) although they're very unlikely to happen.
