### ISSUE TITLE
"ffbtools-master/bin/ffbwrap: invalid option -- 'n'"

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [berarma/ffbtools#16]
Hello, when I run Dirt rally 2.0 (proton 4.11) with the launch option as follows:
ffbtools-master/bin/ffbwrap --update-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick %command%

The game closes itself upon launching, with errors shown in console as follows:

-path-/ffbtools-master/bin/ffbwrap: invalid option -- 'n'
-path-/ffbtools-master/bin/ffbwrap: invalid option -- 'o'
-path-/ffbtools-master/bin/ffbwrap: invalid option -- 'v'
-path-/ffbtools-master/bin/ffbwrap: invalid option -- 'r'

OS: opensuse 15.1. The complilation of the tool went through fine. OK OK need "--" before %command%

**Comment by leillo1975** [comment]
I think you must put "-- %command%" instead "%command%"

**Comment by GreatBigWhiteWorld** [comment]
> I think you must put "-- %command%" instead "%command%"

Exactly. I find it myself in the last minute. Finally the wheel is working great!! Yeeee!

**Comment by GreatBigWhiteWorld** [comment]
Question, what if I need to use "gamemoderun %command%"?
Where do I put "gamemoderun"?

**Comment by leillo1975** [comment]
> > I think you must put "-- %command%" instead "%command%"
> 
> Exactly. I find it myself in the last minute. Finally the wheel is working great!! Yeeee!

I deleted the message because I see that you fixed the problem. 
About your last question, I'm also interested.

**Comment by berarma** [comment]
> Question, what if I need to use "gamemoderun %command%"?
> Where do I put "gamemoderun"?

Then you should use:

`ffbtools-master/bin/ffbwrap --update-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick -- gamemoderun %command%`
