### ISSUE TITLE
Project Cars 2 Log (378860)

### ISSUE THREAD

**Issue by leillo1975** [berarma/ffbtools#2]
**Name of the game:** Project Cars 2
**Steam ID:** 378860
**Game version:** 1.7.1.1
**Game Type (native/proton/wine):** Proton
**Proton/Wine version:** 4.2-9
**Wheel Model:** Logitech G29
**Compatibility Mode:** None
**Distribution:** Ubuntu 18.04.3
**Kernel version:** 5.0

**Force Feedback present:** No
**Symptoms or Special Notes:** The game is executed without FFB fixes 

[PCars2-20191019130935.log](https://github.com/berarma/ffbtools/files/3746588/PCars2-20191019130935.log)

**Comment by xpander69** [comment]
With project CARS2 my FFB doesnt even work with the direction fix, but the log shows like it wants to put the fix to my Roccat Keyboard lol

[ffb.log-20191022135621.log](https://github.com/berarma/ffbtools/files/3755099/ffb.log-20191022135621.log)

command i use:

`/home/xpander/Build_Projects/ffbtools-master/bin/ffbwrap --logger=/home/xpander/ffb.log --direction-fix /dev/input/by-id/usb-Logitech_G920_Driving_Force_Racing_Wheel_for_Xbox_One_0000c58d7f6b6a4c-event-joystick -- %command%`

**Comment by berarma** [comment]
Please, use always the latest version. It's only the device name that's been fixed.

**Comment by berarma** [comment]
@xpander69, can you please confirm it works with Proton 4.2-9. I've been testing the demo of the game and it works consistently. @leillo1975 has tried it on the full game and it works too on this Proton version.

**Comment by leillo1975** [comment]
Log with --features-hack enabled:
[pCars2-20191029233111.log](https://github.com/berarma/ffbtools/files/3786073/pCars2-20191029233111.log)

**Comment by xpander69** [comment]
Confirming it works with proton 4.2-9. Sorry for super late reply.
I wonder why not with 4.11. DiRT Rally 2.0 for example doesnt work with 4.2-9 and the --update-fix, but works with 4.11-8. Proton seems still hit and miss then :(

**Comment by leillo1975** [comment]
Proton 4.11-7 and 4.11-8 have Ffb broken:
https://github.com/ValveSoftware/Proton/issues/3194

It seems that in the following version this will be fixed
