### ISSUE TITLE
DIRT Rally Log (310560)

### ISSUE THREAD

**Issue by leillo1975** [berarma/ffbtools#3]
**Name of the game:** DIRT Rally
**Steam ID:** 310560
**Game version:** 1.22
**Game Type (native/proton/wine):** Native
**Proton/Wine version:** 
**Wheel Model:** Logitech G29
**Compatibility Mode:** None
**Distribution:** Ubuntu 18.04.3
**Kernel version:** 5.0

**Force Feedback present:** Yes
**Symptoms or Special Notes:** The game is executed without FFB fixes 

[DIRTRally1-20191019131646.log](https://github.com/berarma/ffbtools/files/3746592/DIRTRally1-20191019131646.log)

**Comment by berarma** [comment]
I've been testing the native port and it uses only constant force effects even if the wheel supports more effect types. It would be interesting to see if the Windows version does the same or it's the Feral port converting all effects to constant force.
