### ISSUE TITLE
G923 Xbox/PC Force Feedback Problems

### ISSUE THREAD

**Issue by Ricemeter01** [berarma/ffbtools#37]
When playing Assetto corsa I get, `[25444.118364] logitech-hidpp-device 0003:046D:C26E.000B: Force feedback command queue contains 300 commands, causing substantial delays!` I attempted to use ffbwrap with throttling but with throttling enabled I get no force feedback at all, and I still get command queue messages in dmesg. Weirdly the number will go up but then drop back down.

This is the log file with throttling enabled. Sorry if im missing anything else I should of included.
[-20240601214212.log](https://github.com/user-attachments/files/15524234/-20240601214212.log)

**Comment by berarma** [comment]
You shouldn't be using the update fix. Can you try without it?

Also, I've read somewhere that AC has a setting to configure less FFB updates per second which can fix the problem without any other work arounds.

**Comment by Ricemeter01** [comment]
I did try without it and it was the same result, but I set the ffb skip steps in the launcher to 1 and it fixed the problem I didnt know about the ffb updates thing but it fixed it. Thanks!
