### ISSUE TITLE
KartKraft Log (406350)

### ISSUE THREAD

**Issue by leillo1975** [berarma/ffbtools#4]
**Name of the game:** Kartkraft
**Steam ID:** 406350
**Game version:** 0.1.01938
**Game Type (native/proton/wine):** Proton
**Proton/Wine version:** 4.11-7
**Wheel Model:** Logitech G29
**Compatibility Mode:** None
**Distribution:** Ubuntu 18.04.3
**Kernel version:** 5.0

**Force Feedback present:** No
**Symptoms or Special Notes:** The game is executed without FFB fixes 

[KartKraft-20191019132923.log](https://github.com/berarma/ffbtools/files/3746609/KartKraft-20191019132923.log)

**Comment by berarma** [comment]
This game setups an effect but never updates it. There seems to be something wrong in the game, maybe the FF is disabled in the config or some malfunction when running on Proton.

**Comment by leillo1975** [comment]
The force Feedback is not disabled in game. @xpander69 some months ago record a video and Force Feedback was present (https://github.com/ValveSoftware/Proton/issues/2886#issuecomment-530137928). After a few updates, the game lost this functionality
