### ISSUE TITLE
How to use ffbplay

### ISSUE THREAD

**Issue by D3rJust1n** [berarma/ffbtools#43]
Hey, I have a Moza R3 Base and would like to test it. In the ffbplay page it says -d <device>, when I enter the name of the USB device I get the message “no such file or directory”, which points to src/ffbplay.c:811

How to use the command correctly?

Best regards Justin
![image](https://github.com/user-attachments/assets/7ae9fa3d-ac75-444f-b239-714f57c57148)

**Comment by berarma** [comment]
It's not the name of the device that you have to put there. it is the path to the entry in the dev directory. Usually `/dev/input/`...

**Comment by D3rJust1n** [comment]
Okay, but how can i find out which input my Moza Wheelbase is?

**Comment by berarma** [comment]
> ~Okay, but how can i find out which input my Moza Wheelbase is?~ nvm, found it with help of a friend

Good. Anyway, just for reference, in ' /dev/input/by-id' the entries are listed by device name.
