### ISSUE TITLE
RACE 07 Log (8600)

### ISSUE THREAD

**Issue by leillo1975** [berarma/ffbtools#5]
**Name of the game:** RACE 07
**Steam ID:** 8600
**Game version:** 1.2.1.10
**Game Type (native/proton/wine):** Proton
**Proton/Wine version:** 4.2-9
**Wheel Model:** Logitech G29
**Compatibility Mode:** None
**Distribution:** Ubuntu 18.04.3
**Kernel version:** 5.0

**Force Feedback present:** No
**Symptoms or Special Notes:** The game is executed without FFB fixes 

[RACE07-20191020125702.log](https://github.com/berarma/ffbtools/files/3747762/RACE07-20191020125702.log)

**Comment by berarma** [comment]
The log shows calls that should result in some FFB playing. Maybe it's only working when the car is crashing?

It'd be interesting to see a log with `--features-hack` on.

**Comment by leillo1975** [comment]
You say, you command:
[RACE07-20191028000415.log](https://github.com/berarma/ffbtools/files/3776559/RACE07-20191028000415.log)

**Comment by berarma** [comment]
This game uses RUMBLE, SPRING, DAMPER, FRICTION and CONSTANT. It seems to filter out the effects not supported by the wheel. In case of the wheels using the `hid-logitech` module that means it only uses CONSTANT and that's probably the reason there's only FF in crashes.
